/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AlertRegistry {
  export type AlertStruct = {
    wallet: AddressLike;
    entityId: BytesLike;
    severity: BigNumberish;
    ruleHash: BytesLike;
    timestamp: BigNumberish;
    status: BigNumberish;
    resolutionHash: BytesLike;
  };

  export type AlertStructOutput = [
    wallet: string,
    entityId: string,
    severity: bigint,
    ruleHash: string,
    timestamp: bigint,
    status: bigint,
    resolutionHash: string
  ] & {
    wallet: string;
    entityId: string;
    severity: bigint;
    ruleHash: string;
    timestamp: bigint;
    status: bigint;
    resolutionHash: string;
  };
}

export interface AlertRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COMPLIANCE_ADMIN"
      | "DAO_COUNCIL"
      | "DEFAULT_ADMIN_ROLE"
      | "LEGAL_AUDITOR"
      | "MONITORING_ADMIN"
      | "actionPolicy"
      | "alertOf"
      | "autoActionsEnabled"
      | "closeAlert"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "raiseAlert"
      | "renounceRole"
      | "revokeRole"
      | "riskScoreRegistry"
      | "setActionPolicy"
      | "setAutoActionsEnabled"
      | "setRiskScoreRegistry"
      | "supportsInterface"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ActionPolicySet"
      | "AlertClosed"
      | "AlertRaised"
      | "AutoActionExecuted"
      | "AutoActionsEnabled"
      | "RiskScoreRegistrySet"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "COMPLIANCE_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DAO_COUNCIL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LEGAL_AUDITOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MONITORING_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "actionPolicy",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "alertOf", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "autoActionsEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "closeAlert",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "raiseAlert",
    values: [BytesLike, AddressLike, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "riskScoreRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setActionPolicy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAutoActionsEnabled",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setRiskScoreRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "COMPLIANCE_ADMIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DAO_COUNCIL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LEGAL_AUDITOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MONITORING_ADMIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "actionPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "alertOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "autoActionsEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "closeAlert", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "raiseAlert", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "riskScoreRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setActionPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAutoActionsEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRiskScoreRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
}

export namespace ActionPolicySetEvent {
  export type InputTuple = [policy: AddressLike];
  export type OutputTuple = [policy: string];
  export interface OutputObject {
    policy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AlertClosedEvent {
  export type InputTuple = [
    alertId: BytesLike,
    resolutionHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    alertId: string,
    resolutionHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    alertId: string;
    resolutionHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AlertRaisedEvent {
  export type InputTuple = [
    alertId: BytesLike,
    wallet: AddressLike,
    entityId: BytesLike,
    severity: BigNumberish,
    ruleHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    alertId: string,
    wallet: string,
    entityId: string,
    severity: bigint,
    ruleHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    alertId: string;
    wallet: string;
    entityId: string;
    severity: bigint;
    ruleHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AutoActionExecutedEvent {
  export type InputTuple = [
    alertId: BytesLike,
    action: BigNumberish,
    targetRiskLevel: BigNumberish,
    validUntil: BigNumberish
  ];
  export type OutputTuple = [
    alertId: string,
    action: bigint,
    targetRiskLevel: bigint,
    validUntil: bigint
  ];
  export interface OutputObject {
    alertId: string;
    action: bigint;
    targetRiskLevel: bigint;
    validUntil: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AutoActionsEnabledEvent {
  export type InputTuple = [enabled: boolean];
  export type OutputTuple = [enabled: boolean];
  export interface OutputObject {
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskScoreRegistrySetEvent {
  export type InputTuple = [registry: AddressLike];
  export type OutputTuple = [registry: string];
  export interface OutputObject {
    registry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AlertRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AlertRegistry;
  waitForDeployment(): Promise<this>;

  interface: AlertRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COMPLIANCE_ADMIN: TypedContractMethod<[], [string], "view">;

  DAO_COUNCIL: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  LEGAL_AUDITOR: TypedContractMethod<[], [string], "view">;

  MONITORING_ADMIN: TypedContractMethod<[], [string], "view">;

  actionPolicy: TypedContractMethod<[], [string], "view">;

  alertOf: TypedContractMethod<
    [alertId: BytesLike],
    [AlertRegistry.AlertStructOutput],
    "view"
  >;

  autoActionsEnabled: TypedContractMethod<[], [boolean], "view">;

  closeAlert: TypedContractMethod<
    [alertId: BytesLike, resolutionHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  raiseAlert: TypedContractMethod<
    [
      alertId: BytesLike,
      wallet: AddressLike,
      entityId: BytesLike,
      severity: BigNumberish,
      ruleHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  riskScoreRegistry: TypedContractMethod<[], [string], "view">;

  setActionPolicy: TypedContractMethod<
    [policy: AddressLike],
    [void],
    "nonpayable"
  >;

  setAutoActionsEnabled: TypedContractMethod<
    [enabled: boolean],
    [void],
    "nonpayable"
  >;

  setRiskScoreRegistry: TypedContractMethod<
    [registry: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COMPLIANCE_ADMIN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DAO_COUNCIL"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LEGAL_AUDITOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MONITORING_ADMIN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "actionPolicy"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "alertOf"
  ): TypedContractMethod<
    [alertId: BytesLike],
    [AlertRegistry.AlertStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "autoActionsEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "closeAlert"
  ): TypedContractMethod<
    [alertId: BytesLike, resolutionHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "raiseAlert"
  ): TypedContractMethod<
    [
      alertId: BytesLike,
      wallet: AddressLike,
      entityId: BytesLike,
      severity: BigNumberish,
      ruleHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "riskScoreRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setActionPolicy"
  ): TypedContractMethod<[policy: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAutoActionsEnabled"
  ): TypedContractMethod<[enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRiskScoreRegistry"
  ): TypedContractMethod<[registry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;

  getEvent(
    key: "ActionPolicySet"
  ): TypedContractEvent<
    ActionPolicySetEvent.InputTuple,
    ActionPolicySetEvent.OutputTuple,
    ActionPolicySetEvent.OutputObject
  >;
  getEvent(
    key: "AlertClosed"
  ): TypedContractEvent<
    AlertClosedEvent.InputTuple,
    AlertClosedEvent.OutputTuple,
    AlertClosedEvent.OutputObject
  >;
  getEvent(
    key: "AlertRaised"
  ): TypedContractEvent<
    AlertRaisedEvent.InputTuple,
    AlertRaisedEvent.OutputTuple,
    AlertRaisedEvent.OutputObject
  >;
  getEvent(
    key: "AutoActionExecuted"
  ): TypedContractEvent<
    AutoActionExecutedEvent.InputTuple,
    AutoActionExecutedEvent.OutputTuple,
    AutoActionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "AutoActionsEnabled"
  ): TypedContractEvent<
    AutoActionsEnabledEvent.InputTuple,
    AutoActionsEnabledEvent.OutputTuple,
    AutoActionsEnabledEvent.OutputObject
  >;
  getEvent(
    key: "RiskScoreRegistrySet"
  ): TypedContractEvent<
    RiskScoreRegistrySetEvent.InputTuple,
    RiskScoreRegistrySetEvent.OutputTuple,
    RiskScoreRegistrySetEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "ActionPolicySet(address)": TypedContractEvent<
      ActionPolicySetEvent.InputTuple,
      ActionPolicySetEvent.OutputTuple,
      ActionPolicySetEvent.OutputObject
    >;
    ActionPolicySet: TypedContractEvent<
      ActionPolicySetEvent.InputTuple,
      ActionPolicySetEvent.OutputTuple,
      ActionPolicySetEvent.OutputObject
    >;

    "AlertClosed(bytes32,bytes32,uint64)": TypedContractEvent<
      AlertClosedEvent.InputTuple,
      AlertClosedEvent.OutputTuple,
      AlertClosedEvent.OutputObject
    >;
    AlertClosed: TypedContractEvent<
      AlertClosedEvent.InputTuple,
      AlertClosedEvent.OutputTuple,
      AlertClosedEvent.OutputObject
    >;

    "AlertRaised(bytes32,address,bytes32,uint8,bytes32,uint64)": TypedContractEvent<
      AlertRaisedEvent.InputTuple,
      AlertRaisedEvent.OutputTuple,
      AlertRaisedEvent.OutputObject
    >;
    AlertRaised: TypedContractEvent<
      AlertRaisedEvent.InputTuple,
      AlertRaisedEvent.OutputTuple,
      AlertRaisedEvent.OutputObject
    >;

    "AutoActionExecuted(bytes32,uint8,uint8,uint64)": TypedContractEvent<
      AutoActionExecutedEvent.InputTuple,
      AutoActionExecutedEvent.OutputTuple,
      AutoActionExecutedEvent.OutputObject
    >;
    AutoActionExecuted: TypedContractEvent<
      AutoActionExecutedEvent.InputTuple,
      AutoActionExecutedEvent.OutputTuple,
      AutoActionExecutedEvent.OutputObject
    >;

    "AutoActionsEnabled(bool)": TypedContractEvent<
      AutoActionsEnabledEvent.InputTuple,
      AutoActionsEnabledEvent.OutputTuple,
      AutoActionsEnabledEvent.OutputObject
    >;
    AutoActionsEnabled: TypedContractEvent<
      AutoActionsEnabledEvent.InputTuple,
      AutoActionsEnabledEvent.OutputTuple,
      AutoActionsEnabledEvent.OutputObject
    >;

    "RiskScoreRegistrySet(address)": TypedContractEvent<
      RiskScoreRegistrySetEvent.InputTuple,
      RiskScoreRegistrySetEvent.OutputTuple,
      RiskScoreRegistrySetEvent.OutputObject
    >;
    RiskScoreRegistrySet: TypedContractEvent<
      RiskScoreRegistrySetEvent.InputTuple,
      RiskScoreRegistrySetEvent.OutputTuple,
      RiskScoreRegistrySetEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
