/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace CatalystIdentitySBT {
  export type IdentityInfoStruct = {
    userTypeCode: BigNumberish;
    kycLevelCode: BigNumberish;
    status: BigNumberish;
    validUntil: BigNumberish;
    attestationHash: BytesLike;
    updatedAt: BigNumberish;
    reasonHash: BytesLike;
  };

  export type IdentityInfoStructOutput = [
    userTypeCode: bigint,
    kycLevelCode: bigint,
    status: bigint,
    validUntil: bigint,
    attestationHash: string,
    updatedAt: bigint,
    reasonHash: string
  ] & {
    userTypeCode: bigint;
    kycLevelCode: bigint;
    status: bigint;
    validUntil: bigint;
    attestationHash: string;
    updatedAt: bigint;
    reasonHash: string;
  };
}

export interface CatalystIdentitySBTInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COMPLIANCE_ADMIN"
      | "DAO_COUNCIL"
      | "DEFAULT_ADMIN_ROLE"
      | "IDENTITY_MINTER"
      | "LEGAL_AUDITOR"
      | "approve"
      | "balanceOf"
      | "getApproved"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "identityInfo"
      | "identityRecordOf"
      | "isApprovedForAll"
      | "isIdentityValid"
      | "markExpired"
      | "mintIdentity"
      | "name"
      | "ownerOf"
      | "renewIdentity"
      | "renounceRole"
      | "revokeIdentity"
      | "revokeRole"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "supportsInterface"
      | "suspendIdentity"
      | "symbol"
      | "tokenIdOf"
      | "tokenURI"
      | "transferFrom"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "ApprovalForAll"
      | "IdentityExpired"
      | "IdentityMinted"
      | "IdentityRenewed"
      | "IdentityRevoked"
      | "IdentitySuspended"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Transfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "COMPLIANCE_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DAO_COUNCIL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "IDENTITY_MINTER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LEGAL_AUDITOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "identityInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "identityRecordOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isIdentityValid",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markExpired",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintIdentity",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renewIdentity",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeIdentity",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "suspendIdentity",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenIdOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "COMPLIANCE_ADMIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DAO_COUNCIL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "IDENTITY_MINTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LEGAL_AUDITOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "identityInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "identityRecordOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isIdentityValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markExpired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renewIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "suspendIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenIdOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityExpiredEvent {
  export type InputTuple = [wallet: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [wallet: string, timestamp: bigint];
  export interface OutputObject {
    wallet: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityMintedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    tokenId: BigNumberish,
    userTypeCode: BigNumberish,
    kycLevelCode: BigNumberish,
    validUntil: BigNumberish,
    attestationHash: BytesLike
  ];
  export type OutputTuple = [
    wallet: string,
    tokenId: bigint,
    userTypeCode: bigint,
    kycLevelCode: bigint,
    validUntil: bigint,
    attestationHash: string
  ];
  export interface OutputObject {
    wallet: string;
    tokenId: bigint;
    userTypeCode: bigint;
    kycLevelCode: bigint;
    validUntil: bigint;
    attestationHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityRenewedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    validUntil: BigNumberish,
    attestationHash: BytesLike
  ];
  export type OutputTuple = [
    wallet: string,
    validUntil: bigint,
    attestationHash: string
  ];
  export interface OutputObject {
    wallet: string;
    validUntil: bigint;
    attestationHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityRevokedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    reasonHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    wallet: string,
    reasonHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    wallet: string;
    reasonHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentitySuspendedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    reasonHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    wallet: string,
    reasonHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    wallet: string;
    reasonHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CatalystIdentitySBT extends BaseContract {
  connect(runner?: ContractRunner | null): CatalystIdentitySBT;
  waitForDeployment(): Promise<this>;

  interface: CatalystIdentitySBTInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COMPLIANCE_ADMIN: TypedContractMethod<[], [string], "view">;

  DAO_COUNCIL: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  IDENTITY_MINTER: TypedContractMethod<[], [string], "view">;

  LEGAL_AUDITOR: TypedContractMethod<[], [string], "view">;

  approve: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [void],
    "view"
  >;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  identityInfo: TypedContractMethod<
    [wallet: AddressLike],
    [
      [bigint, bigint, bigint, bigint, string] & {
        userTypeCode: bigint;
        kycLevelCode: bigint;
        status: bigint;
        validUntil: bigint;
        attestationHash: string;
      }
    ],
    "view"
  >;

  identityRecordOf: TypedContractMethod<
    [wallet: AddressLike],
    [CatalystIdentitySBT.IdentityInfoStructOutput],
    "view"
  >;

  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  isIdentityValid: TypedContractMethod<
    [wallet: AddressLike],
    [boolean],
    "view"
  >;

  markExpired: TypedContractMethod<[wallet: AddressLike], [void], "nonpayable">;

  mintIdentity: TypedContractMethod<
    [
      wallet: AddressLike,
      userTypeCode: BigNumberish,
      kycLevelCode: BigNumberish,
      validUntil: BigNumberish,
      attestationHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  renewIdentity: TypedContractMethod<
    [
      wallet: AddressLike,
      newValidUntil: BigNumberish,
      newAttestationHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeIdentity: TypedContractMethod<
    [wallet: AddressLike, reasonHash: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [void],
    "view"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [void],
    "view"
  >;

  setApprovalForAll: TypedContractMethod<
    [arg0: AddressLike, arg1: boolean],
    [void],
    "view"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  suspendIdentity: TypedContractMethod<
    [wallet: AddressLike, reasonHash: BytesLike],
    [void],
    "nonpayable"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  tokenIdOf: TypedContractMethod<[wallet: AddressLike], [bigint], "view">;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  transferFrom: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [void],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COMPLIANCE_ADMIN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DAO_COUNCIL"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "IDENTITY_MINTER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LEGAL_AUDITOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "identityInfo"
  ): TypedContractMethod<
    [wallet: AddressLike],
    [
      [bigint, bigint, bigint, bigint, string] & {
        userTypeCode: bigint;
        kycLevelCode: bigint;
        status: bigint;
        validUntil: bigint;
        attestationHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "identityRecordOf"
  ): TypedContractMethod<
    [wallet: AddressLike],
    [CatalystIdentitySBT.IdentityInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isIdentityValid"
  ): TypedContractMethod<[wallet: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "markExpired"
  ): TypedContractMethod<[wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "mintIdentity"
  ): TypedContractMethod<
    [
      wallet: AddressLike,
      userTypeCode: BigNumberish,
      kycLevelCode: BigNumberish,
      validUntil: BigNumberish,
      attestationHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "renewIdentity"
  ): TypedContractMethod<
    [
      wallet: AddressLike,
      newValidUntil: BigNumberish,
      newAttestationHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeIdentity"
  ): TypedContractMethod<
    [wallet: AddressLike, reasonHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<[arg0: AddressLike, arg1: boolean], [void], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "suspendIdentity"
  ): TypedContractMethod<
    [wallet: AddressLike, reasonHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenIdOf"
  ): TypedContractMethod<[wallet: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [void],
    "view"
  >;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "IdentityExpired"
  ): TypedContractEvent<
    IdentityExpiredEvent.InputTuple,
    IdentityExpiredEvent.OutputTuple,
    IdentityExpiredEvent.OutputObject
  >;
  getEvent(
    key: "IdentityMinted"
  ): TypedContractEvent<
    IdentityMintedEvent.InputTuple,
    IdentityMintedEvent.OutputTuple,
    IdentityMintedEvent.OutputObject
  >;
  getEvent(
    key: "IdentityRenewed"
  ): TypedContractEvent<
    IdentityRenewedEvent.InputTuple,
    IdentityRenewedEvent.OutputTuple,
    IdentityRenewedEvent.OutputObject
  >;
  getEvent(
    key: "IdentityRevoked"
  ): TypedContractEvent<
    IdentityRevokedEvent.InputTuple,
    IdentityRevokedEvent.OutputTuple,
    IdentityRevokedEvent.OutputObject
  >;
  getEvent(
    key: "IdentitySuspended"
  ): TypedContractEvent<
    IdentitySuspendedEvent.InputTuple,
    IdentitySuspendedEvent.OutputTuple,
    IdentitySuspendedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "IdentityExpired(address,uint64)": TypedContractEvent<
      IdentityExpiredEvent.InputTuple,
      IdentityExpiredEvent.OutputTuple,
      IdentityExpiredEvent.OutputObject
    >;
    IdentityExpired: TypedContractEvent<
      IdentityExpiredEvent.InputTuple,
      IdentityExpiredEvent.OutputTuple,
      IdentityExpiredEvent.OutputObject
    >;

    "IdentityMinted(address,uint256,uint8,uint8,uint64,bytes32)": TypedContractEvent<
      IdentityMintedEvent.InputTuple,
      IdentityMintedEvent.OutputTuple,
      IdentityMintedEvent.OutputObject
    >;
    IdentityMinted: TypedContractEvent<
      IdentityMintedEvent.InputTuple,
      IdentityMintedEvent.OutputTuple,
      IdentityMintedEvent.OutputObject
    >;

    "IdentityRenewed(address,uint64,bytes32)": TypedContractEvent<
      IdentityRenewedEvent.InputTuple,
      IdentityRenewedEvent.OutputTuple,
      IdentityRenewedEvent.OutputObject
    >;
    IdentityRenewed: TypedContractEvent<
      IdentityRenewedEvent.InputTuple,
      IdentityRenewedEvent.OutputTuple,
      IdentityRenewedEvent.OutputObject
    >;

    "IdentityRevoked(address,bytes32,uint64)": TypedContractEvent<
      IdentityRevokedEvent.InputTuple,
      IdentityRevokedEvent.OutputTuple,
      IdentityRevokedEvent.OutputObject
    >;
    IdentityRevoked: TypedContractEvent<
      IdentityRevokedEvent.InputTuple,
      IdentityRevokedEvent.OutputTuple,
      IdentityRevokedEvent.OutputObject
    >;

    "IdentitySuspended(address,bytes32,uint64)": TypedContractEvent<
      IdentitySuspendedEvent.InputTuple,
      IdentitySuspendedEvent.OutputTuple,
      IdentitySuspendedEvent.OutputObject
    >;
    IdentitySuspended: TypedContractEvent<
      IdentitySuspendedEvent.InputTuple,
      IdentitySuspendedEvent.OutputTuple,
      IdentitySuspendedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
