/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ComplianceGateInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "credentialRegistry"
      | "enforcementEnabled"
      | "entityRegistry"
      | "eventRegistry"
      | "identityRegistry"
      | "maxAllowedRisk"
      | "requiredCredentialRole"
      | "roleAuthority"
      | "scoringRegistry"
      | "setEntityRegistry"
      | "setEventRegistry"
      | "setPolicy"
      | "setRegistries"
      | "setRoleAuthority"
      | "setUBORegistry"
      | "uboRegistry"
      | "validate"
      | "validateWithEvent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EntityRegistryUpdated"
      | "EventRegistryUpdated"
      | "GateConfigured"
      | "GatePolicyUpdated"
      | "RoleAuthorityUpdated"
      | "UBORegistryUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "credentialRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "enforcementEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "eventRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxAllowedRisk",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requiredCredentialRole",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "roleAuthority",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "scoringRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setEntityRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setEventRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPolicy",
    values: [boolean, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRegistries",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRoleAuthority",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setUBORegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "uboRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "validate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validateWithEvent",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "credentialRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enforcementEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eventRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxAllowedRisk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requiredCredentialRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "roleAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scoringRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEntityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEventRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPolicy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setRegistries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRoleAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUBORegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uboRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "validate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validateWithEvent",
    data: BytesLike
  ): Result;
}

export namespace EntityRegistryUpdatedEvent {
  export type InputTuple = [entityRegistry: AddressLike];
  export type OutputTuple = [entityRegistry: string];
  export interface OutputObject {
    entityRegistry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EventRegistryUpdatedEvent {
  export type InputTuple = [eventRegistry: AddressLike];
  export type OutputTuple = [eventRegistry: string];
  export interface OutputObject {
    eventRegistry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GateConfiguredEvent {
  export type InputTuple = [
    identityRegistry: AddressLike,
    scoringRegistry: AddressLike,
    credentialRegistry: AddressLike
  ];
  export type OutputTuple = [
    identityRegistry: string,
    scoringRegistry: string,
    credentialRegistry: string
  ];
  export interface OutputObject {
    identityRegistry: string;
    scoringRegistry: string;
    credentialRegistry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GatePolicyUpdatedEvent {
  export type InputTuple = [
    enforcementEnabled: boolean,
    maxAllowedRisk: BigNumberish,
    requiredCredentialRole: BytesLike
  ];
  export type OutputTuple = [
    enforcementEnabled: boolean,
    maxAllowedRisk: bigint,
    requiredCredentialRole: string
  ];
  export interface OutputObject {
    enforcementEnabled: boolean;
    maxAllowedRisk: bigint;
    requiredCredentialRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAuthorityUpdatedEvent {
  export type InputTuple = [roleAuthority: AddressLike];
  export type OutputTuple = [roleAuthority: string];
  export interface OutputObject {
    roleAuthority: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UBORegistryUpdatedEvent {
  export type InputTuple = [uboRegistry: AddressLike];
  export type OutputTuple = [uboRegistry: string];
  export interface OutputObject {
    uboRegistry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ComplianceGate extends BaseContract {
  connect(runner?: ContractRunner | null): ComplianceGate;
  waitForDeployment(): Promise<this>;

  interface: ComplianceGateInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  credentialRegistry: TypedContractMethod<[], [string], "view">;

  enforcementEnabled: TypedContractMethod<[], [boolean], "view">;

  entityRegistry: TypedContractMethod<[], [string], "view">;

  eventRegistry: TypedContractMethod<[], [string], "view">;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  maxAllowedRisk: TypedContractMethod<[], [bigint], "view">;

  requiredCredentialRole: TypedContractMethod<[], [string], "view">;

  roleAuthority: TypedContractMethod<[], [string], "view">;

  scoringRegistry: TypedContractMethod<[], [string], "view">;

  setEntityRegistry: TypedContractMethod<
    [entityRegistry_: AddressLike],
    [void],
    "nonpayable"
  >;

  setEventRegistry: TypedContractMethod<
    [eventRegistry_: AddressLike],
    [void],
    "nonpayable"
  >;

  setPolicy: TypedContractMethod<
    [
      enforcementEnabled_: boolean,
      maxAllowedRisk_: BigNumberish,
      requiredCredentialRole_: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setRegistries: TypedContractMethod<
    [
      identityRegistry_: AddressLike,
      scoringRegistry_: AddressLike,
      credentialRegistry_: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  setRoleAuthority: TypedContractMethod<
    [roleAuthority_: AddressLike],
    [void],
    "nonpayable"
  >;

  setUBORegistry: TypedContractMethod<
    [uboRegistry_: AddressLike],
    [void],
    "nonpayable"
  >;

  uboRegistry: TypedContractMethod<[], [string], "view">;

  validate: TypedContractMethod<[wallet: AddressLike], [void], "view">;

  validateWithEvent: TypedContractMethod<
    [wallet: AddressLike, eid: BytesLike],
    [void],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "credentialRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "enforcementEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "entityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "eventRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "maxAllowedRisk"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requiredCredentialRole"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "roleAuthority"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "scoringRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setEntityRegistry"
  ): TypedContractMethod<[entityRegistry_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEventRegistry"
  ): TypedContractMethod<[eventRegistry_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPolicy"
  ): TypedContractMethod<
    [
      enforcementEnabled_: boolean,
      maxAllowedRisk_: BigNumberish,
      requiredCredentialRole_: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRegistries"
  ): TypedContractMethod<
    [
      identityRegistry_: AddressLike,
      scoringRegistry_: AddressLike,
      credentialRegistry_: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRoleAuthority"
  ): TypedContractMethod<[roleAuthority_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUBORegistry"
  ): TypedContractMethod<[uboRegistry_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "uboRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "validate"
  ): TypedContractMethod<[wallet: AddressLike], [void], "view">;
  getFunction(
    nameOrSignature: "validateWithEvent"
  ): TypedContractMethod<[wallet: AddressLike, eid: BytesLike], [void], "view">;

  getEvent(
    key: "EntityRegistryUpdated"
  ): TypedContractEvent<
    EntityRegistryUpdatedEvent.InputTuple,
    EntityRegistryUpdatedEvent.OutputTuple,
    EntityRegistryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EventRegistryUpdated"
  ): TypedContractEvent<
    EventRegistryUpdatedEvent.InputTuple,
    EventRegistryUpdatedEvent.OutputTuple,
    EventRegistryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "GateConfigured"
  ): TypedContractEvent<
    GateConfiguredEvent.InputTuple,
    GateConfiguredEvent.OutputTuple,
    GateConfiguredEvent.OutputObject
  >;
  getEvent(
    key: "GatePolicyUpdated"
  ): TypedContractEvent<
    GatePolicyUpdatedEvent.InputTuple,
    GatePolicyUpdatedEvent.OutputTuple,
    GatePolicyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAuthorityUpdated"
  ): TypedContractEvent<
    RoleAuthorityUpdatedEvent.InputTuple,
    RoleAuthorityUpdatedEvent.OutputTuple,
    RoleAuthorityUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "UBORegistryUpdated"
  ): TypedContractEvent<
    UBORegistryUpdatedEvent.InputTuple,
    UBORegistryUpdatedEvent.OutputTuple,
    UBORegistryUpdatedEvent.OutputObject
  >;

  filters: {
    "EntityRegistryUpdated(address)": TypedContractEvent<
      EntityRegistryUpdatedEvent.InputTuple,
      EntityRegistryUpdatedEvent.OutputTuple,
      EntityRegistryUpdatedEvent.OutputObject
    >;
    EntityRegistryUpdated: TypedContractEvent<
      EntityRegistryUpdatedEvent.InputTuple,
      EntityRegistryUpdatedEvent.OutputTuple,
      EntityRegistryUpdatedEvent.OutputObject
    >;

    "EventRegistryUpdated(address)": TypedContractEvent<
      EventRegistryUpdatedEvent.InputTuple,
      EventRegistryUpdatedEvent.OutputTuple,
      EventRegistryUpdatedEvent.OutputObject
    >;
    EventRegistryUpdated: TypedContractEvent<
      EventRegistryUpdatedEvent.InputTuple,
      EventRegistryUpdatedEvent.OutputTuple,
      EventRegistryUpdatedEvent.OutputObject
    >;

    "GateConfigured(address,address,address)": TypedContractEvent<
      GateConfiguredEvent.InputTuple,
      GateConfiguredEvent.OutputTuple,
      GateConfiguredEvent.OutputObject
    >;
    GateConfigured: TypedContractEvent<
      GateConfiguredEvent.InputTuple,
      GateConfiguredEvent.OutputTuple,
      GateConfiguredEvent.OutputObject
    >;

    "GatePolicyUpdated(bool,uint8,bytes32)": TypedContractEvent<
      GatePolicyUpdatedEvent.InputTuple,
      GatePolicyUpdatedEvent.OutputTuple,
      GatePolicyUpdatedEvent.OutputObject
    >;
    GatePolicyUpdated: TypedContractEvent<
      GatePolicyUpdatedEvent.InputTuple,
      GatePolicyUpdatedEvent.OutputTuple,
      GatePolicyUpdatedEvent.OutputObject
    >;

    "RoleAuthorityUpdated(address)": TypedContractEvent<
      RoleAuthorityUpdatedEvent.InputTuple,
      RoleAuthorityUpdatedEvent.OutputTuple,
      RoleAuthorityUpdatedEvent.OutputObject
    >;
    RoleAuthorityUpdated: TypedContractEvent<
      RoleAuthorityUpdatedEvent.InputTuple,
      RoleAuthorityUpdatedEvent.OutputTuple,
      RoleAuthorityUpdatedEvent.OutputObject
    >;

    "UBORegistryUpdated(address)": TypedContractEvent<
      UBORegistryUpdatedEvent.InputTuple,
      UBORegistryUpdatedEvent.OutputTuple,
      UBORegistryUpdatedEvent.OutputObject
    >;
    UBORegistryUpdated: TypedContractEvent<
      UBORegistryUpdatedEvent.InputTuple,
      UBORegistryUpdatedEvent.OutputTuple,
      UBORegistryUpdatedEvent.OutputObject
    >;
  };
}
