/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FRTAuditTrailInterface extends Interface {
  getFunction(
    nameOrSignature: "emitAuditRecord" | "fractalToken"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AuditTrail"): EventFragment;

  encodeFunctionData(
    functionFragment: "emitAuditRecord",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fractalToken",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "emitAuditRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fractalToken",
    data: BytesLike
  ): Result;
}

export namespace AuditTrailEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    operationType: BigNumberish,
    purposeHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    amount: bigint,
    operationType: bigint,
    purposeHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    from: string;
    to: string;
    amount: bigint;
    operationType: bigint;
    purposeHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FRTAuditTrail extends BaseContract {
  connect(runner?: ContractRunner | null): FRTAuditTrail;
  waitForDeployment(): Promise<this>;

  interface: FRTAuditTrailInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  emitAuditRecord: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      operationType: BigNumberish,
      purposeHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  fractalToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "emitAuditRecord"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      operationType: BigNumberish,
      purposeHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fractalToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AuditTrail"
  ): TypedContractEvent<
    AuditTrailEvent.InputTuple,
    AuditTrailEvent.OutputTuple,
    AuditTrailEvent.OutputObject
  >;

  filters: {
    "AuditTrail(address,address,uint256,uint8,bytes32,uint256)": TypedContractEvent<
      AuditTrailEvent.InputTuple,
      AuditTrailEvent.OutputTuple,
      AuditTrailEvent.OutputObject
    >;
    AuditTrail: TypedContractEvent<
      AuditTrailEvent.InputTuple,
      AuditTrailEvent.OutputTuple,
      AuditTrailEvent.OutputObject
    >;
  };
}
