/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MultisigCouncilInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approvals"
      | "approveSensitiveProposal"
      | "approvedBy"
      | "changeGuardian"
      | "guardian"
      | "hasEnoughApprovals"
      | "isCouncilSigner"
      | "isGuardian"
      | "isMember"
      | "members"
      | "threshold"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "GuardianChanged" | "ProposalSigned"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approvals",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approveSensitiveProposal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approvedBy",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "changeGuardian",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "guardian", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "hasEnoughApprovals",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCouncilSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isGuardian",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMember",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "members",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "threshold", values?: undefined): string;

  decodeFunctionResult(functionFragment: "approvals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveSensitiveProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approvedBy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "guardian", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasEnoughApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCouncilSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isGuardian", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isMember", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "members", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "threshold", data: BytesLike): Result;
}

export namespace GuardianChangedEvent {
  export type InputTuple = [oldGuardian: AddressLike, newGuardian: AddressLike];
  export type OutputTuple = [oldGuardian: string, newGuardian: string];
  export interface OutputObject {
    oldGuardian: string;
    newGuardian: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalSignedEvent {
  export type InputTuple = [proposalHash: BytesLike, signer: AddressLike];
  export type OutputTuple = [proposalHash: string, signer: string];
  export interface OutputObject {
    proposalHash: string;
    signer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MultisigCouncil extends BaseContract {
  connect(runner?: ContractRunner | null): MultisigCouncil;
  waitForDeployment(): Promise<this>;

  interface: MultisigCouncilInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approvals: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  approveSensitiveProposal: TypedContractMethod<
    [proposalHash: BytesLike],
    [void],
    "nonpayable"
  >;

  approvedBy: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  changeGuardian: TypedContractMethod<
    [newGuardian: AddressLike],
    [void],
    "nonpayable"
  >;

  guardian: TypedContractMethod<[], [string], "view">;

  hasEnoughApprovals: TypedContractMethod<
    [proposalHash: BytesLike],
    [boolean],
    "view"
  >;

  isCouncilSigner: TypedContractMethod<
    [account: AddressLike],
    [boolean],
    "view"
  >;

  isGuardian: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  isMember: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  members: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  threshold: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approvals"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "approveSensitiveProposal"
  ): TypedContractMethod<[proposalHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approvedBy"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "changeGuardian"
  ): TypedContractMethod<[newGuardian: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "guardian"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "hasEnoughApprovals"
  ): TypedContractMethod<[proposalHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isCouncilSigner"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isGuardian"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isMember"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "members"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "threshold"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "GuardianChanged"
  ): TypedContractEvent<
    GuardianChangedEvent.InputTuple,
    GuardianChangedEvent.OutputTuple,
    GuardianChangedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalSigned"
  ): TypedContractEvent<
    ProposalSignedEvent.InputTuple,
    ProposalSignedEvent.OutputTuple,
    ProposalSignedEvent.OutputObject
  >;

  filters: {
    "GuardianChanged(address,address)": TypedContractEvent<
      GuardianChangedEvent.InputTuple,
      GuardianChangedEvent.OutputTuple,
      GuardianChangedEvent.OutputObject
    >;
    GuardianChanged: TypedContractEvent<
      GuardianChangedEvent.InputTuple,
      GuardianChangedEvent.OutputTuple,
      GuardianChangedEvent.OutputObject
    >;

    "ProposalSigned(bytes32,address)": TypedContractEvent<
      ProposalSignedEvent.InputTuple,
      ProposalSignedEvent.OutputTuple,
      ProposalSignedEvent.OutputObject
    >;
    ProposalSigned: TypedContractEvent<
      ProposalSignedEvent.InputTuple,
      ProposalSignedEvent.OutputTuple,
      ProposalSignedEvent.OutputObject
    >;
  };
}
