/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface OperationsRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "AUDIT_ADMIN"
      | "COMPLIANCE_ADMIN"
      | "DAO_COUNCIL"
      | "DEFAULT_ADMIN_ROLE"
      | "LEGAL_AUDITOR"
      | "OPERATIONS_ADMIN"
      | "activeJurisdictions"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "isJurisdictionActive"
      | "lastAuditTimestamp"
      | "operationalStatus"
      | "recordAuditCheckpoint"
      | "renounceRole"
      | "revokeRole"
      | "setJurisdiction"
      | "setOperationalStatus"
      | "supportsInterface"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuditCheckpointRecorded"
      | "JurisdictionStatusChanged"
      | "OperationsStatusChanged"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "AUDIT_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "COMPLIANCE_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DAO_COUNCIL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LEGAL_AUDITOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPERATIONS_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeJurisdictions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isJurisdictionActive",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastAuditTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "operationalStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordAuditCheckpoint",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setJurisdiction",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setOperationalStatus",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "AUDIT_ADMIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "COMPLIANCE_ADMIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DAO_COUNCIL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LEGAL_AUDITOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPERATIONS_ADMIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeJurisdictions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isJurisdictionActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastAuditTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "operationalStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordAuditCheckpoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setJurisdiction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOperationalStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
}

export namespace AuditCheckpointRecordedEvent {
  export type InputTuple = [
    checkpointId: BytesLike,
    scope: BytesLike,
    evidenceHash: BytesLike,
    periodStart: BigNumberish,
    periodEnd: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    checkpointId: string,
    scope: string,
    evidenceHash: string,
    periodStart: bigint,
    periodEnd: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    checkpointId: string;
    scope: string;
    evidenceHash: string;
    periodStart: bigint;
    periodEnd: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JurisdictionStatusChangedEvent {
  export type InputTuple = [jurisdiction: BytesLike, active: boolean];
  export type OutputTuple = [jurisdiction: string, active: boolean];
  export interface OutputObject {
    jurisdiction: string;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperationsStatusChangedEvent {
  export type InputTuple = [
    status: BigNumberish,
    reasonHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    status: bigint,
    reasonHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    status: bigint;
    reasonHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OperationsRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): OperationsRegistry;
  waitForDeployment(): Promise<this>;

  interface: OperationsRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  AUDIT_ADMIN: TypedContractMethod<[], [string], "view">;

  COMPLIANCE_ADMIN: TypedContractMethod<[], [string], "view">;

  DAO_COUNCIL: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  LEGAL_AUDITOR: TypedContractMethod<[], [string], "view">;

  OPERATIONS_ADMIN: TypedContractMethod<[], [string], "view">;

  activeJurisdictions: TypedContractMethod<[], [string[]], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isJurisdictionActive: TypedContractMethod<
    [jurisdiction: BytesLike],
    [boolean],
    "view"
  >;

  lastAuditTimestamp: TypedContractMethod<[], [bigint], "view">;

  operationalStatus: TypedContractMethod<[], [bigint], "view">;

  recordAuditCheckpoint: TypedContractMethod<
    [
      checkpointId: BytesLike,
      scope: BytesLike,
      evidenceHash: BytesLike,
      periodStart: BigNumberish,
      periodEnd: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setJurisdiction: TypedContractMethod<
    [jurisdiction: BytesLike, active: boolean],
    [void],
    "nonpayable"
  >;

  setOperationalStatus: TypedContractMethod<
    [status: BigNumberish, reasonHash: BytesLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "AUDIT_ADMIN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "COMPLIANCE_ADMIN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DAO_COUNCIL"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LEGAL_AUDITOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OPERATIONS_ADMIN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "activeJurisdictions"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isJurisdictionActive"
  ): TypedContractMethod<[jurisdiction: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastAuditTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "operationalStatus"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordAuditCheckpoint"
  ): TypedContractMethod<
    [
      checkpointId: BytesLike,
      scope: BytesLike,
      evidenceHash: BytesLike,
      periodStart: BigNumberish,
      periodEnd: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setJurisdiction"
  ): TypedContractMethod<
    [jurisdiction: BytesLike, active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOperationalStatus"
  ): TypedContractMethod<
    [status: BigNumberish, reasonHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;

  getEvent(
    key: "AuditCheckpointRecorded"
  ): TypedContractEvent<
    AuditCheckpointRecordedEvent.InputTuple,
    AuditCheckpointRecordedEvent.OutputTuple,
    AuditCheckpointRecordedEvent.OutputObject
  >;
  getEvent(
    key: "JurisdictionStatusChanged"
  ): TypedContractEvent<
    JurisdictionStatusChangedEvent.InputTuple,
    JurisdictionStatusChangedEvent.OutputTuple,
    JurisdictionStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "OperationsStatusChanged"
  ): TypedContractEvent<
    OperationsStatusChangedEvent.InputTuple,
    OperationsStatusChangedEvent.OutputTuple,
    OperationsStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "AuditCheckpointRecorded(bytes32,bytes32,bytes32,uint64,uint64,uint64)": TypedContractEvent<
      AuditCheckpointRecordedEvent.InputTuple,
      AuditCheckpointRecordedEvent.OutputTuple,
      AuditCheckpointRecordedEvent.OutputObject
    >;
    AuditCheckpointRecorded: TypedContractEvent<
      AuditCheckpointRecordedEvent.InputTuple,
      AuditCheckpointRecordedEvent.OutputTuple,
      AuditCheckpointRecordedEvent.OutputObject
    >;

    "JurisdictionStatusChanged(bytes32,bool)": TypedContractEvent<
      JurisdictionStatusChangedEvent.InputTuple,
      JurisdictionStatusChangedEvent.OutputTuple,
      JurisdictionStatusChangedEvent.OutputObject
    >;
    JurisdictionStatusChanged: TypedContractEvent<
      JurisdictionStatusChangedEvent.InputTuple,
      JurisdictionStatusChangedEvent.OutputTuple,
      JurisdictionStatusChangedEvent.OutputObject
    >;

    "OperationsStatusChanged(uint8,bytes32,uint64)": TypedContractEvent<
      OperationsStatusChangedEvent.InputTuple,
      OperationsStatusChangedEvent.OutputTuple,
      OperationsStatusChangedEvent.OutputObject
    >;
    OperationsStatusChanged: TypedContractEvent<
      OperationsStatusChangedEvent.InputTuple,
      OperationsStatusChangedEvent.OutputTuple,
      OperationsStatusChangedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
