/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace WhitelistPolicy {
  export type PolicyStruct = {
    disclosuresRequired: boolean;
    complianceRequired: boolean;
    riskScoreRequired: boolean;
    maxRiskLevel: BigNumberish;
    eligibilityRequired: boolean;
    travelRuleRequired: boolean;
    offeringId: BytesLike;
    policyHash: BytesLike;
    version: BigNumberish;
    exists: boolean;
  };

  export type PolicyStructOutput = [
    disclosuresRequired: boolean,
    complianceRequired: boolean,
    riskScoreRequired: boolean,
    maxRiskLevel: bigint,
    eligibilityRequired: boolean,
    travelRuleRequired: boolean,
    offeringId: string,
    policyHash: string,
    version: bigint,
    exists: boolean
  ] & {
    disclosuresRequired: boolean;
    complianceRequired: boolean;
    riskScoreRequired: boolean;
    maxRiskLevel: bigint;
    eligibilityRequired: boolean;
    travelRuleRequired: boolean;
    offeringId: string;
    policyHash: string;
    version: bigint;
    exists: boolean;
  };
}

export interface WhitelistPolicyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COMPLIANCE_ADMIN"
      | "DAO_COUNCIL"
      | "DEFAULT_ADMIN_ROLE"
      | "LEGAL_AUDITOR"
      | "WHITELIST_ADMIN"
      | "acceptanceRegistry"
      | "activatePolicy"
      | "activePolicy"
      | "activePolicyVersion"
      | "complianceGate"
      | "disclosureRegistry"
      | "eligibilityRegistry"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "offeringRegistry"
      | "publishPolicy"
      | "renounceRole"
      | "revokeRole"
      | "riskScoreRegistry"
      | "setAcceptanceRegistry"
      | "setComplianceGate"
      | "setDisclosureRegistry"
      | "setEligibilityRegistry"
      | "setOfferingRegistry"
      | "setRiskScoreRegistry"
      | "setTravelRuleGate"
      | "supportsInterface"
      | "travelRuleGate"
      | "validateTransfer"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AcceptanceRegistrySet"
      | "ComplianceGateSet"
      | "DisclosureRegistrySet"
      | "EligibilityRegistrySet"
      | "OfferingRegistrySet"
      | "RiskScoreRegistrySet"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TravelRuleGateSet"
      | "WhitelistPolicyActivated"
      | "WhitelistPolicyPublished"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "COMPLIANCE_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DAO_COUNCIL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LEGAL_AUDITOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WHITELIST_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptanceRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activatePolicy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "activePolicy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activePolicyVersion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "complianceGate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "disclosureRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "eligibilityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "offeringRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publishPolicy",
    values: [
      boolean,
      boolean,
      boolean,
      BigNumberish,
      boolean,
      boolean,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "riskScoreRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAcceptanceRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setComplianceGate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDisclosureRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setEligibilityRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOfferingRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRiskScoreRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTravelRuleGate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "travelRuleGate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "validateTransfer",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "COMPLIANCE_ADMIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DAO_COUNCIL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LEGAL_AUDITOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WHITELIST_ADMIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptanceRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activatePolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activePolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activePolicyVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "complianceGate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disclosureRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eligibilityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "offeringRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publishPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "riskScoreRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAcceptanceRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setComplianceGate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDisclosureRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEligibilityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOfferingRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRiskScoreRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTravelRuleGate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "travelRuleGate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateTransfer",
    data: BytesLike
  ): Result;
}

export namespace AcceptanceRegistrySetEvent {
  export type InputTuple = [registry: AddressLike];
  export type OutputTuple = [registry: string];
  export interface OutputObject {
    registry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplianceGateSetEvent {
  export type InputTuple = [gate: AddressLike];
  export type OutputTuple = [gate: string];
  export interface OutputObject {
    gate: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisclosureRegistrySetEvent {
  export type InputTuple = [registry: AddressLike];
  export type OutputTuple = [registry: string];
  export interface OutputObject {
    registry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EligibilityRegistrySetEvent {
  export type InputTuple = [registry: AddressLike];
  export type OutputTuple = [registry: string];
  export interface OutputObject {
    registry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfferingRegistrySetEvent {
  export type InputTuple = [registry: AddressLike];
  export type OutputTuple = [registry: string];
  export interface OutputObject {
    registry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskScoreRegistrySetEvent {
  export type InputTuple = [registry: AddressLike];
  export type OutputTuple = [registry: string];
  export interface OutputObject {
    registry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TravelRuleGateSetEvent {
  export type InputTuple = [gate: AddressLike];
  export type OutputTuple = [gate: string];
  export interface OutputObject {
    gate: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistPolicyActivatedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistPolicyPublishedEvent {
  export type InputTuple = [version: BigNumberish, policyHash: BytesLike];
  export type OutputTuple = [version: bigint, policyHash: string];
  export interface OutputObject {
    version: bigint;
    policyHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WhitelistPolicy extends BaseContract {
  connect(runner?: ContractRunner | null): WhitelistPolicy;
  waitForDeployment(): Promise<this>;

  interface: WhitelistPolicyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COMPLIANCE_ADMIN: TypedContractMethod<[], [string], "view">;

  DAO_COUNCIL: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  LEGAL_AUDITOR: TypedContractMethod<[], [string], "view">;

  WHITELIST_ADMIN: TypedContractMethod<[], [string], "view">;

  acceptanceRegistry: TypedContractMethod<[], [string], "view">;

  activatePolicy: TypedContractMethod<
    [version: BigNumberish],
    [void],
    "nonpayable"
  >;

  activePolicy: TypedContractMethod<
    [],
    [WhitelistPolicy.PolicyStructOutput],
    "view"
  >;

  activePolicyVersion: TypedContractMethod<[], [bigint], "view">;

  complianceGate: TypedContractMethod<[], [string], "view">;

  disclosureRegistry: TypedContractMethod<[], [string], "view">;

  eligibilityRegistry: TypedContractMethod<[], [string], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  offeringRegistry: TypedContractMethod<[], [string], "view">;

  publishPolicy: TypedContractMethod<
    [
      disclosuresRequired: boolean,
      complianceRequired: boolean,
      riskScoreRequired: boolean,
      maxRiskLevel: BigNumberish,
      eligibilityRequired: boolean,
      travelRuleRequired: boolean,
      offeringId: BytesLike,
      policyHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  riskScoreRegistry: TypedContractMethod<[], [string], "view">;

  setAcceptanceRegistry: TypedContractMethod<
    [registry: AddressLike],
    [void],
    "nonpayable"
  >;

  setComplianceGate: TypedContractMethod<
    [gate: AddressLike],
    [void],
    "nonpayable"
  >;

  setDisclosureRegistry: TypedContractMethod<
    [registry: AddressLike],
    [void],
    "nonpayable"
  >;

  setEligibilityRegistry: TypedContractMethod<
    [registry: AddressLike],
    [void],
    "nonpayable"
  >;

  setOfferingRegistry: TypedContractMethod<
    [registry: AddressLike],
    [void],
    "nonpayable"
  >;

  setRiskScoreRegistry: TypedContractMethod<
    [registry: AddressLike],
    [void],
    "nonpayable"
  >;

  setTravelRuleGate: TypedContractMethod<
    [gate: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  travelRuleGate: TypedContractMethod<[], [string], "view">;

  validateTransfer: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      assetType: BytesLike,
      travelEvidenceId: BytesLike
    ],
    [void],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COMPLIANCE_ADMIN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DAO_COUNCIL"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LEGAL_AUDITOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "WHITELIST_ADMIN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptanceRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "activatePolicy"
  ): TypedContractMethod<[version: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "activePolicy"
  ): TypedContractMethod<[], [WhitelistPolicy.PolicyStructOutput], "view">;
  getFunction(
    nameOrSignature: "activePolicyVersion"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "complianceGate"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "disclosureRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "eligibilityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "offeringRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "publishPolicy"
  ): TypedContractMethod<
    [
      disclosuresRequired: boolean,
      complianceRequired: boolean,
      riskScoreRequired: boolean,
      maxRiskLevel: BigNumberish,
      eligibilityRequired: boolean,
      travelRuleRequired: boolean,
      offeringId: BytesLike,
      policyHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "riskScoreRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAcceptanceRegistry"
  ): TypedContractMethod<[registry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setComplianceGate"
  ): TypedContractMethod<[gate: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDisclosureRegistry"
  ): TypedContractMethod<[registry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEligibilityRegistry"
  ): TypedContractMethod<[registry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOfferingRegistry"
  ): TypedContractMethod<[registry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRiskScoreRegistry"
  ): TypedContractMethod<[registry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTravelRuleGate"
  ): TypedContractMethod<[gate: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "travelRuleGate"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "validateTransfer"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      assetType: BytesLike,
      travelEvidenceId: BytesLike
    ],
    [void],
    "view"
  >;

  getEvent(
    key: "AcceptanceRegistrySet"
  ): TypedContractEvent<
    AcceptanceRegistrySetEvent.InputTuple,
    AcceptanceRegistrySetEvent.OutputTuple,
    AcceptanceRegistrySetEvent.OutputObject
  >;
  getEvent(
    key: "ComplianceGateSet"
  ): TypedContractEvent<
    ComplianceGateSetEvent.InputTuple,
    ComplianceGateSetEvent.OutputTuple,
    ComplianceGateSetEvent.OutputObject
  >;
  getEvent(
    key: "DisclosureRegistrySet"
  ): TypedContractEvent<
    DisclosureRegistrySetEvent.InputTuple,
    DisclosureRegistrySetEvent.OutputTuple,
    DisclosureRegistrySetEvent.OutputObject
  >;
  getEvent(
    key: "EligibilityRegistrySet"
  ): TypedContractEvent<
    EligibilityRegistrySetEvent.InputTuple,
    EligibilityRegistrySetEvent.OutputTuple,
    EligibilityRegistrySetEvent.OutputObject
  >;
  getEvent(
    key: "OfferingRegistrySet"
  ): TypedContractEvent<
    OfferingRegistrySetEvent.InputTuple,
    OfferingRegistrySetEvent.OutputTuple,
    OfferingRegistrySetEvent.OutputObject
  >;
  getEvent(
    key: "RiskScoreRegistrySet"
  ): TypedContractEvent<
    RiskScoreRegistrySetEvent.InputTuple,
    RiskScoreRegistrySetEvent.OutputTuple,
    RiskScoreRegistrySetEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TravelRuleGateSet"
  ): TypedContractEvent<
    TravelRuleGateSetEvent.InputTuple,
    TravelRuleGateSetEvent.OutputTuple,
    TravelRuleGateSetEvent.OutputObject
  >;
  getEvent(
    key: "WhitelistPolicyActivated"
  ): TypedContractEvent<
    WhitelistPolicyActivatedEvent.InputTuple,
    WhitelistPolicyActivatedEvent.OutputTuple,
    WhitelistPolicyActivatedEvent.OutputObject
  >;
  getEvent(
    key: "WhitelistPolicyPublished"
  ): TypedContractEvent<
    WhitelistPolicyPublishedEvent.InputTuple,
    WhitelistPolicyPublishedEvent.OutputTuple,
    WhitelistPolicyPublishedEvent.OutputObject
  >;

  filters: {
    "AcceptanceRegistrySet(address)": TypedContractEvent<
      AcceptanceRegistrySetEvent.InputTuple,
      AcceptanceRegistrySetEvent.OutputTuple,
      AcceptanceRegistrySetEvent.OutputObject
    >;
    AcceptanceRegistrySet: TypedContractEvent<
      AcceptanceRegistrySetEvent.InputTuple,
      AcceptanceRegistrySetEvent.OutputTuple,
      AcceptanceRegistrySetEvent.OutputObject
    >;

    "ComplianceGateSet(address)": TypedContractEvent<
      ComplianceGateSetEvent.InputTuple,
      ComplianceGateSetEvent.OutputTuple,
      ComplianceGateSetEvent.OutputObject
    >;
    ComplianceGateSet: TypedContractEvent<
      ComplianceGateSetEvent.InputTuple,
      ComplianceGateSetEvent.OutputTuple,
      ComplianceGateSetEvent.OutputObject
    >;

    "DisclosureRegistrySet(address)": TypedContractEvent<
      DisclosureRegistrySetEvent.InputTuple,
      DisclosureRegistrySetEvent.OutputTuple,
      DisclosureRegistrySetEvent.OutputObject
    >;
    DisclosureRegistrySet: TypedContractEvent<
      DisclosureRegistrySetEvent.InputTuple,
      DisclosureRegistrySetEvent.OutputTuple,
      DisclosureRegistrySetEvent.OutputObject
    >;

    "EligibilityRegistrySet(address)": TypedContractEvent<
      EligibilityRegistrySetEvent.InputTuple,
      EligibilityRegistrySetEvent.OutputTuple,
      EligibilityRegistrySetEvent.OutputObject
    >;
    EligibilityRegistrySet: TypedContractEvent<
      EligibilityRegistrySetEvent.InputTuple,
      EligibilityRegistrySetEvent.OutputTuple,
      EligibilityRegistrySetEvent.OutputObject
    >;

    "OfferingRegistrySet(address)": TypedContractEvent<
      OfferingRegistrySetEvent.InputTuple,
      OfferingRegistrySetEvent.OutputTuple,
      OfferingRegistrySetEvent.OutputObject
    >;
    OfferingRegistrySet: TypedContractEvent<
      OfferingRegistrySetEvent.InputTuple,
      OfferingRegistrySetEvent.OutputTuple,
      OfferingRegistrySetEvent.OutputObject
    >;

    "RiskScoreRegistrySet(address)": TypedContractEvent<
      RiskScoreRegistrySetEvent.InputTuple,
      RiskScoreRegistrySetEvent.OutputTuple,
      RiskScoreRegistrySetEvent.OutputObject
    >;
    RiskScoreRegistrySet: TypedContractEvent<
      RiskScoreRegistrySetEvent.InputTuple,
      RiskScoreRegistrySetEvent.OutputTuple,
      RiskScoreRegistrySetEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TravelRuleGateSet(address)": TypedContractEvent<
      TravelRuleGateSetEvent.InputTuple,
      TravelRuleGateSetEvent.OutputTuple,
      TravelRuleGateSetEvent.OutputObject
    >;
    TravelRuleGateSet: TypedContractEvent<
      TravelRuleGateSetEvent.InputTuple,
      TravelRuleGateSetEvent.OutputTuple,
      TravelRuleGateSetEvent.OutputObject
    >;

    "WhitelistPolicyActivated(uint32)": TypedContractEvent<
      WhitelistPolicyActivatedEvent.InputTuple,
      WhitelistPolicyActivatedEvent.OutputTuple,
      WhitelistPolicyActivatedEvent.OutputObject
    >;
    WhitelistPolicyActivated: TypedContractEvent<
      WhitelistPolicyActivatedEvent.InputTuple,
      WhitelistPolicyActivatedEvent.OutputTuple,
      WhitelistPolicyActivatedEvent.OutputObject
    >;

    "WhitelistPolicyPublished(uint32,bytes32)": TypedContractEvent<
      WhitelistPolicyPublishedEvent.InputTuple,
      WhitelistPolicyPublishedEvent.OutputTuple,
      WhitelistPolicyPublishedEvent.OutputObject
    >;
    WhitelistPolicyPublished: TypedContractEvent<
      WhitelistPolicyPublishedEvent.InputTuple,
      WhitelistPolicyPublishedEvent.OutputTuple,
      WhitelistPolicyPublishedEvent.OutputObject
    >;
  };
}
