from base64 import b64encode
from typing import Dict, Tuple, Optional

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.asymmetric.utils import Prehashed
from cryptography.exceptions import InvalidSignature


class FractalSigner:
    """Utility for signing messages along with symbolic metadata using ECDSA.

    The message is concatenated with sorted metadata values, hashed with
    ``SHA3-512`` and then signed using the ``SECP256R1`` curve.

    Example
    -------
    >>> from cryptography.hazmat.primitives.asymmetric import ec
    >>> key = ec.generate_private_key(ec.SECP256R1())
    >>> meta = {"arquetipo": "custodio", "proposito": "ritual"}
    >>> signature, info = FractalSigner.sign_message("hola", meta, key, True)
    >>> FractalSigner.verify_signature("hola", meta, signature, key.public_key())
    True
    """

    @staticmethod
    def _prepare(message: str, metadata: Dict[str, str]) -> bytes:
        meta_sorted = ''.join(f"{k}:{v}" for k, v in sorted(metadata.items()))
        return (message + meta_sorted).encode('utf-8')

    @staticmethod
    def sign_message(
        message: str,
        metadata: Dict[str, str],
        private_key: ec.EllipticCurvePrivateKey,
        export_json: bool = False,
    ) -> Tuple[bytes, Optional[dict]]:
        """Sign a message and metadata.

        Parameters
        ----------
        message: str
            Text to sign.
        metadata: dict
            Symbolic metadata (e.g. ``{"dao": "root"}``).
        private_key: EllipticCurvePrivateKey
            ECDSA private key on ``SECP256R1``.
        export_json: bool
            If ``True``, return a dictionary with signature details.

        Returns
        -------
        tuple
            ``(signature_bytes, json_dict_or_None)``

        Example
        -------
        >>> key = ec.generate_private_key(ec.SECP256R1())
        >>> sig, data = FractalSigner.sign_message("msg", {}, key, True)
        """
        data = FractalSigner._prepare(message, metadata)
        digest = hashes.Hash(hashes.SHA3_512())
        digest.update(data)
        msg_hash = digest.finalize()
        signature = private_key.sign(msg_hash, ec.ECDSA(Prehashed(hashes.SHA3_512())))

        info = None
        if export_json:
            pub_bytes = private_key.public_key().public_bytes(
                encoding=serialization.Encoding.PEM,
                format=serialization.PublicFormat.SubjectPublicKeyInfo,
            )
            info = {
                "firma_base64": b64encode(signature).decode('utf-8'),
                "hash_previo": msg_hash.hex(),
                "estructura_metadata": dict(sorted(metadata.items())),
                "direccion_publica": pub_bytes.decode('utf-8'),
            }
        return signature, info

    @staticmethod
    def verify_signature(
        message: str,
        metadata: Dict[str, str],
        signature: bytes,
        public_key: ec.EllipticCurvePublicKey,
    ) -> bool:
        """Verify a signature generated by :meth:`sign_message`.

        Example
        -------
        >>> key = ec.generate_private_key(ec.SECP256R1())
        >>> sig, _ = FractalSigner.sign_message("hola", {}, key)
        >>> FractalSigner.verify_signature("hola", {}, sig, key.public_key())
        True
        """
        data = FractalSigner._prepare(message, metadata)
        digest = hashes.Hash(hashes.SHA3_512())
        digest.update(data)
        msg_hash = digest.finalize()
        try:
            public_key.verify(signature, msg_hash, ec.ECDSA(Prehashed(hashes.SHA3_512())))
            return True
        except InvalidSignature:
            return False

