from __future__ import annotations

from datetime import datetime
from pathlib import Path

from markdown_it import MarkdownIt

from app.core.config import Settings
from app.core.models import Event, ModuleStatus, Policy, SystemStatus

BASE_TEMPLATE = Path(__file__).parent / "templates" / "base.html"


def render_dashboard_html(
    system_status: SystemStatus,
    statuses: list[ModuleStatus],
    policies: list[Policy],
    events: list[Event],
    settings: Settings,
) -> str:
    markdown = build_markdown(system_status, statuses, policies, events, settings)
    renderer = MarkdownIt("commonmark", {"html": True})
    content_html = renderer.render(markdown)
    template = BASE_TEMPLATE.read_text(encoding="utf-8")
    html = template.replace("{{content}}", content_html).replace(
        "{{title}}", "Catalyst Blockchain Core"
    )
    return html


def build_markdown(
    system_status: SystemStatus,
    statuses: list[ModuleStatus],
    policies: list[Policy],
    events: list[Event],
    settings: Settings,
) -> str:
    policy_map = {policy.id: policy for policy in policies}
    status_map = {status.name: status for status in statuses}

    def policy_line(policy_id: str, label: str) -> str:
        policy = policy_map.get(policy_id)
        if not policy:
            return f"- {label}: UNKNOWN"
        detail = f" ({policy.detail})" if policy.detail else ""
        return f"- {label}: {policy.status}{detail}"

    def status_line(module_id: str, label: str) -> str:
        status = status_map.get(module_id)
        if not status:
            return f"- {label}: UNKNOWN"
        return f"- {label}: {status.status} ({status.detail})"

    last_updated = system_status.updated_at.isoformat()
    nav = [
        '<nav class="nav-tabs">',
        '<a href="#general">General</a>',
        '<a href="#compliance">Compliance</a>',
        '<a href="#identity">Identity</a>',
        '<a href="#tokens">Tokens</a>',
        '<a href="#restrictions">Restrictions</a>',
        '<a href="#freeze">Freeze</a>',
        '<a href="#governance">Governance</a>',
        '<a href="#trust">Trust</a>',
        '<a href="#listing">Listing</a>',
        '<a href="#simulation">Simulation</a>',
        '<a href="#audit">Audit</a>',
        '<a href="#arcade">Arcade</a>',
        '<a href="#events">Events</a>',
        "</nav>",
    ]
    token_chart = [
        '<section class="panel">',
        "<h3>Token Activity (Mock)</h3>",
        '<canvas id="tokenChart" width="860" height="240" aria-label="Token activity chart"></canvas>',
        "</section>",
        '<script>',
        "const tokenChart = document.getElementById('tokenChart');",
        "if (tokenChart) {",
        "  const ctx = tokenChart.getContext('2d');",
        "  const labels = ['W1','W2','W3','W4','W5','W6','W7'];",
        "  const totalSupply = [1.0,1.0,1.02,1.03,1.05,1.06,1.06];",
        "  const circulating = [0.6,0.62,0.63,0.66,0.68,0.7,0.72];",
        "  const padding = 24;",
        "  const w = tokenChart.width - padding * 2;",
        "  const h = tokenChart.height - padding * 2;",
        "  ctx.clearRect(0,0,tokenChart.width,tokenChart.height);",
        "  ctx.fillStyle = '#071107';",
        "  ctx.fillRect(0,0,tokenChart.width,tokenChart.height);",
        "  ctx.strokeStyle = '#214a21';",
        "  ctx.lineWidth = 1;",
        "  for (let i = 0; i <= 4; i++) {",
        "    const y = padding + (h / 4) * i;",
        "    ctx.beginPath();",
        "    ctx.moveTo(padding, y);",
        "    ctx.lineTo(padding + w, y);",
        "    ctx.stroke();",
        "  }",
        "  const maxVal = 1.1;",
        "  const toXY = (v, i) => {",
        "    const x = padding + (w / (labels.length - 1)) * i;",
        "    const y = padding + h - (v / maxVal) * h;",
        "    return {x, y};",
        "  };",
        "  const drawLine = (series, color) => {",
        "    ctx.strokeStyle = color;",
        "    ctx.lineWidth = 2;",
        "    ctx.beginPath();",
        "    series.forEach((v, i) => {",
        "      const {x, y} = toXY(v, i);",
        "      if (i === 0) ctx.moveTo(x, y); else ctx.lineTo(x, y);",
        "    });",
        "    ctx.stroke();",
        "  };",
        "  drawLine(totalSupply, '#a8ff60');",
        "  drawLine(circulating, '#7dff7d');",
        "  ctx.fillStyle = '#7dff7d';",
        "  ctx.font = '12px Courier New, monospace';",
        "  ctx.fillText('Total Supply', padding, padding - 6);",
        "  ctx.fillStyle = '#a8ff60';",
        "  ctx.fillText('Circulating', padding + 140, padding - 6);",
        "}",
        "</script>",
    ]
    markdown = [
        "# Catalyst Blockchain Core",
        "",
        *nav,
        "",
        f"- Environment: {settings.app_env}",
        f"- Updated: {last_updated}",
        f"- Modules: {system_status.module_count}",
        f"- Policies: {system_status.policy_count}",
        f"- Events: {system_status.event_count}",
        "",
        '<a id="general"></a>',
        "## 1) General Status",
        f"- Status: {system_status.status}",
        status_line("compliance_dao", "Governance Health"),
        status_line("operations_audit", "Audit Health"),
        "",
        '<a id="compliance"></a>',
        "## 2) Compliance",
        policy_line("kyc_aml_gate", "KYC/AML Gate"),
        policy_line("travel_rule", "Travel Rule"),
        "",
        '<a id="identity"></a>',
        "## 3) Identity",
        policy_line("sbt_required", "SBT Required"),
        policy_line("sbt_expiry_enforced", "SBT Expiry"),
        "",
        '<a id="tokens"></a>',
        "## 4) Tokens",
        policy_line("token_symbol", "Symbol"),
        policy_line("token_decimals", "Decimals"),
        policy_line("token_supply", "Total Supply"),
        policy_line("token_minting", "Minting"),
        policy_line("token_enforcement", "Enforcement"),
        "",
        *token_chart,
        "",
        '<a id="restrictions"></a>',
        "## 5) Restrictions",
        policy_line("lockups_active", "Lockups"),
        policy_line("jurisdiction_filter", "Jurisdiction"),
        policy_line("purpose_restriction", "Purpose Restriction"),
        "",
        '<a id="freeze"></a>',
        "## 6) Freeze",
        policy_line("freeze_wallets", "Wallets"),
        policy_line("freeze_series", "Series"),
        policy_line("freeze_functions", "Functions"),
        "",
        '<a id="governance"></a>',
        "## 7) Governance",
        policy_line("dao_quorum", "Quorum"),
        policy_line("vote_period", "Voting Period"),
        policy_line("guardian_enabled", "Guardian Veto"),
        "",
        '<a id="trust"></a>',
        "## 8) Trust",
        policy_line("trust_active", "Trusts"),
        policy_line("revenue_reports", "Revenue Reports"),
        "",
        '<a id="listing"></a>',
        "## 9) Listing",
        policy_line("listing_phase", "Listing Phase"),
        policy_line("venues_allowed", "Venues"),
        "",
        '<a id="simulation"></a>',
        "## 10) Simulation",
        policy_line("ssi_index", "SSI"),
        policy_line("bai_index", "BAI"),
        "",
        '<a id="audit"></a>',
        "## 11) Audit",
        policy_line("audit_checkpoints", "Checkpoints"),
        policy_line("audit_trail", "Audit Trail"),
        "",
        '<a id="arcade"></a>',
        "## 12) Arcade",
        "Galaga-style shooter. Use Arrow keys to move, Space to fire.",
        '<section class="panel arcade-panel">',
        '<canvas id="arcadeGame" width="860" height="360" aria-label="Arcade shooter game"></canvas>',
        "</section>",
        '<section class="panel arcade-panel arcade-ui">',
        '<div class="arcade-row">',
        '<label for="playerKey">Player Key</label>',
        '<input id="playerKey" type="text" maxlength="64" />',
        '<button id="saveKey">Save</button>',
        "</div>",
        '<div class="arcade-row">',
        '<button id="submitScore">Submit Score</button>',
        '<button id="resetGame">Reset Game</button>',
        "</div>",
        '<div id="arcadeStatus" class="arcade-status"></div>',
        '<div id="arcadeReward" class="arcade-reward"></div>',
        '<div id="arcadeLeaderboard" class="arcade-leaderboard"></div>',
        "</section>",
        '<script>',
        "(function(){",
        "  const canvas = document.getElementById('arcadeGame');",
        "  if (!canvas) return;",
        "  const ctx = canvas.getContext('2d');",
        "  const state = {",
        "    keys: {},",
        "    bullets: [],",
        "    enemies: [],",
        "    score: 0,",
        "    lives: 3,",
        "    gameOver: false,",
        "    submitted: false,",
        "    dir: 1,",
        "    speed: 0.6,",
        "    lastShot: 0,",
        "  };",
        "  const player = { x: canvas.width / 2, y: canvas.height - 32, w: 36, h: 18 };",
        "  const playerKeyInput = document.getElementById('playerKey');",
        "  const saveKeyBtn = document.getElementById('saveKey');",
        "  const submitBtn = document.getElementById('submitScore');",
        "  const resetBtn = document.getElementById('resetGame');",
        "  const statusEl = document.getElementById('arcadeStatus');",
        "  const rewardEl = document.getElementById('arcadeReward');",
        "  const leaderboardEl = document.getElementById('arcadeLeaderboard');",
        "  const storageKey = 'catalyst_arcade_player';",
        "  const ensurePlayerKey = () => {",
        "    let key = localStorage.getItem(storageKey);",
        "    if (!key) {",
        "      key = 'PLAYER-' + Math.random().toString(36).slice(2, 10).toUpperCase();",
        "      localStorage.setItem(storageKey, key);",
        "    }",
        "    if (playerKeyInput) playerKeyInput.value = key;",
        "    return key;",
        "  };",
        "  const savePlayerKey = () => {",
        "    if (!playerKeyInput || !statusEl) return;",
        "    const key = playerKeyInput.value.trim();",
        "    if (key.length < 8) {",
        "      statusEl.textContent = 'Player key must be at least 8 characters.';",
        "      return;",
        "    }",
        "    localStorage.setItem(storageKey, key);",
        "    statusEl.textContent = 'Player key saved.';",
        "  };",
        "  const renderLeaderboard = (rows) => {",
        "    if (!leaderboardEl) return;",
        "    if (!rows || !rows.length) {",
        "      leaderboardEl.innerHTML = '<em>No scores yet.</em>';",
        "      return;",
        "    }",
        "    let html = '<table><thead><tr><th>Rank</th><th>Player</th><th>Score</th></tr></thead><tbody>';",
        "    rows.forEach((row, idx) => {",
        "      html += '<tr><td>' + (idx + 1) + '</td><td>' + row.player_id + '</td><td>' + row.score + '</td></tr>';",
        "    });",
        "    html += '</tbody></table>';",
        "    leaderboardEl.innerHTML = html;",
        "  };",
        "  const refreshLeaderboard = () => {",
        "    fetch('/api/arcade/leaderboard')",
        "      .then((r) => r.json())",
        "      .then(renderLeaderboard)",
        "      .catch(() => {});",
        "  };",
        "  const submitScore = () => {",
        "    const key = ensurePlayerKey();",
        "    fetch('/api/arcade/submit', {",
        "      method: 'POST',",
        "      headers: { 'Content-Type': 'application/json' },",
        "      body: JSON.stringify({ player_id: key, score: state.score }),",
        "    })",
        "      .then((r) => r.json())",
        "      .then((data) => {",
        "        if (statusEl) {",
        "          statusEl.textContent = 'Score submitted. Top score: ' + data.top_score + '. Season ends: ' + data.season_end;",
        "        }",
        "        if (rewardEl) {",
        "          rewardEl.textContent = data.reward_message ? data.reward_message : '';",
        "        }",
        "        refreshLeaderboard();",
        "      })",
        "      .catch(() => {",
        "        if (statusEl) statusEl.textContent = 'Score submission failed.';",
        "      });",
        "  };",
        "  if (saveKeyBtn) saveKeyBtn.addEventListener('click', savePlayerKey);",
        "  if (submitBtn) submitBtn.addEventListener('click', submitScore);",
        "  if (resetBtn) resetBtn.addEventListener('click', () => resetGame());",
        "  ensurePlayerKey();",
        "  refreshLeaderboard();",
        "  const spawnEnemies = () => {",
        "    state.enemies = [];",
        "    const rows = 4;",
        "    const cols = 9;",
        "    const gap = 16;",
        "    const startX = 80;",
        "    const startY = 50;",
        "    for (let r = 0; r < rows; r++) {",
        "      for (let c = 0; c < cols; c++) {",
        "        state.enemies.push({",
        "          x: startX + c * (28 + gap),",
        "          y: startY + r * (22 + gap),",
        "          w: 26,",
        "          h: 18,",
        "          alive: true,",
        "        });",
        "      }",
        "    }",
        "  };",
        "  spawnEnemies();",
        "  const onKey = (e, down) => {",
        "    if (['ArrowLeft','ArrowRight','Space','KeyR'].includes(e.code)) {",
        "      state.keys[e.code] = down;",
        "      e.preventDefault();",
        "    }",
        "  };",
        "  window.addEventListener('keydown', (e) => onKey(e, true));",
        "  window.addEventListener('keyup', (e) => onKey(e, false));",
        "  const shoot = (now) => {",
        "    if (now - state.lastShot < 250) return;",
        "    state.lastShot = now;",
        "    state.bullets.push({ x: player.x + player.w / 2 - 2, y: player.y, v: -5 });",
        "  };",
        "  const update = (now) => {",
        "    if (state.gameOver) return;",
        "    if (state.keys['ArrowLeft']) player.x -= 4;",
        "    if (state.keys['ArrowRight']) player.x += 4;",
        "    if (state.keys['Space']) shoot(now);",
        "    player.x = Math.max(10, Math.min(canvas.width - player.w - 10, player.x));",
        "    state.bullets.forEach((b) => (b.y += b.v));",
        "    state.bullets = state.bullets.filter((b) => b.y > -10);",
        "    let hitEdge = false;",
        "    state.enemies.forEach((e) => {",
        "      if (!e.alive) return;",
        "      e.x += state.dir * state.speed;",
        "      if (e.x < 20 || e.x + e.w > canvas.width - 20) hitEdge = true;",
        "    });",
        "    if (hitEdge) {",
        "      state.dir *= -1;",
        "      state.enemies.forEach((e) => {",
        "        if (e.alive) e.y += 12;",
        "      });",
        "    }",
        "    const reachedBottom = state.enemies.some((e) => e.alive && e.y + e.h >= player.y);",
        "    if (reachedBottom) {",
        "      state.lives -= 1;",
        "      if (state.lives <= 0) {",
        "        state.gameOver = true;",
        "        if (!state.submitted) {",
        "          state.submitted = true;",
        "          submitScore();",
        "        }",
        "      } else {",
        "        spawnEnemies();",
        "      }",
        "    }",
        "    state.bullets.forEach((b) => {",
        "      state.enemies.forEach((e) => {",
        "        if (!e.alive) return;",
        "        if (b.x < e.x + e.w && b.x + 4 > e.x && b.y < e.y + e.h && b.y + 8 > e.y) {",
        "          e.alive = false;",
        "          b.y = -20;",
        "          state.score += 10;",
        "        }",
        "      });",
        "    });",
        "    if (state.enemies.every((e) => !e.alive)) {",
        "      state.speed += 0.2;",
        "      spawnEnemies();",
        "    }",
        "  };",
        "  const draw = () => {",
        "    ctx.fillStyle = '#070f07';",
        "    ctx.fillRect(0, 0, canvas.width, canvas.height);",
        "    ctx.fillStyle = '#7dff7d';",
        "    ctx.fillRect(player.x, player.y, player.w, player.h);",
        "    ctx.fillStyle = '#a8ff60';",
        "    state.enemies.forEach((e) => {",
        "      if (e.alive) ctx.fillRect(e.x, e.y, e.w, e.h);",
        "    });",
        "    ctx.fillStyle = '#ffffff';",
        "    state.bullets.forEach((b) => ctx.fillRect(b.x, b.y, 4, 8));",
        "    ctx.fillStyle = '#7dff7d';",
        "    ctx.font = '12px Courier New, monospace';",
        "    ctx.fillText(`Score: ${state.score}`, 16, 20);",
        "    ctx.fillText(`Lives: ${state.lives}`, canvas.width - 120, 20);",
        "    if (state.gameOver) {",
        "      ctx.fillStyle = '#a8ff60';",
        "      ctx.font = '18px Courier New, monospace';",
        "      ctx.fillText('GAME OVER - Press R to Restart', 180, canvas.height / 2);",
        "    }",
        "  };",
        "  const resetGame = () => {",
        "    state.score = 0;",
        "    state.lives = 3;",
        "    state.gameOver = false;",
        "    state.submitted = false;",
        "    state.bullets = [];",
        "    state.speed = 0.6;",
        "    spawnEnemies();",
        "    if (statusEl) statusEl.textContent = 'Game reset.';",
        "  };",
        "  let last = performance.now();",
        "  const loop = (now) => {",
        "    const delta = now - last;",
        "    if (delta > 16) {",
        "      if (state.keys['KeyR'] && state.gameOver) {",
        "        resetGame();",
        "      }",
        "      update(now);",
        "      draw();",
        "      last = now;",
        "    }",
        "    requestAnimationFrame(loop);",
        "  };",
        "  loop(performance.now());",
        "})();",
        "</script>",
        "",
        '<a id="events"></a>',
        "## 13) Recent Events",
        "",
        build_event_table(events),
    ]
    return "\n".join(markdown)


def build_event_table(events: list[Event]) -> str:
    if not events:
        return "_No events yet._"

    rows = ["| Time | Module | Type | Severity | Message |", "| --- | --- | --- | --- | --- |"]
    for event in events[:10]:
        timestamp = _format_time(event.timestamp)
        rows.append(
            f"| {timestamp} | {event.module} | {event.type} | {event.severity} | {event.message} |"
        )
    return "\n".join(rows)


def _format_time(value: datetime) -> str:
    if isinstance(value, datetime):
        return value.isoformat(timespec="seconds")
    return str(value)
