/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IRiskPolicyRegistry {
  export type PolicyStruct = {
    maxAmountPerPeriod: BigNumberish;
    maxTxPerPeriod: BigNumberish;
    periodSeconds: BigNumberish;
    allowedActions: BigNumberish;
    version: BigNumberish;
    policyHash: BytesLike;
    exists: boolean;
  };

  export type PolicyStructOutput = [
    maxAmountPerPeriod: bigint,
    maxTxPerPeriod: bigint,
    periodSeconds: bigint,
    allowedActions: bigint,
    version: bigint,
    policyHash: string,
    exists: boolean
  ] & {
    maxAmountPerPeriod: bigint;
    maxTxPerPeriod: bigint;
    periodSeconds: bigint;
    allowedActions: bigint;
    version: bigint;
    policyHash: string;
    exists: boolean;
  };
}

export interface IRiskPolicyRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "activePolicy" | "activePolicyVersion"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "activePolicy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "activePolicyVersion",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "activePolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activePolicyVersion",
    data: BytesLike
  ): Result;
}

export interface IRiskPolicyRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IRiskPolicyRegistry;
  waitForDeployment(): Promise<this>;

  interface: IRiskPolicyRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activePolicy: TypedContractMethod<
    [level: BigNumberish],
    [IRiskPolicyRegistry.PolicyStructOutput],
    "view"
  >;

  activePolicyVersion: TypedContractMethod<
    [level: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activePolicy"
  ): TypedContractMethod<
    [level: BigNumberish],
    [IRiskPolicyRegistry.PolicyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "activePolicyVersion"
  ): TypedContractMethod<[level: BigNumberish], [bigint], "view">;

  filters: {};
}
