/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ITokenUsePolicyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "disclosuresRequired"
      | "isJurisdictionAllowed"
      | "isPurposeAllowed"
      | "jurisdictionRequired"
      | "lockupRequired"
      | "lockupUntil"
      | "paymentRestricted"
      | "whitelistRequired"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "disclosuresRequired",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isJurisdictionAllowed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPurposeAllowed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "jurisdictionRequired",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lockupRequired",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lockupUntil",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "paymentRestricted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistRequired",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "disclosuresRequired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isJurisdictionAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPurposeAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "jurisdictionRequired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockupRequired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockupUntil",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "paymentRestricted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistRequired",
    data: BytesLike
  ): Result;
}

export interface ITokenUsePolicy extends BaseContract {
  connect(runner?: ContractRunner | null): ITokenUsePolicy;
  waitForDeployment(): Promise<this>;

  interface: ITokenUsePolicyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  disclosuresRequired: TypedContractMethod<[], [boolean], "view">;

  isJurisdictionAllowed: TypedContractMethod<
    [wallet: AddressLike],
    [boolean],
    "view"
  >;

  isPurposeAllowed: TypedContractMethod<
    [purposeHash: BytesLike],
    [boolean],
    "view"
  >;

  jurisdictionRequired: TypedContractMethod<[], [boolean], "view">;

  lockupRequired: TypedContractMethod<[], [boolean], "view">;

  lockupUntil: TypedContractMethod<[wallet: AddressLike], [bigint], "view">;

  paymentRestricted: TypedContractMethod<[], [boolean], "view">;

  whitelistRequired: TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "disclosuresRequired"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isJurisdictionAllowed"
  ): TypedContractMethod<[wallet: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPurposeAllowed"
  ): TypedContractMethod<[purposeHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "jurisdictionRequired"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lockupRequired"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lockupUntil"
  ): TypedContractMethod<[wallet: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "paymentRestricted"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "whitelistRequired"
  ): TypedContractMethod<[], [boolean], "view">;

  filters: {};
}
