/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ITransferRestrictionPolicyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "eligibilityRequired"
      | "enforcementEnabled"
      | "jurisdictionRequired"
      | "lockupUntil"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "eligibilityRequired",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "enforcementEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "jurisdictionRequired",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lockupUntil",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "eligibilityRequired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enforcementEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "jurisdictionRequired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockupUntil",
    data: BytesLike
  ): Result;
}

export interface ITransferRestrictionPolicy extends BaseContract {
  connect(runner?: ContractRunner | null): ITransferRestrictionPolicy;
  waitForDeployment(): Promise<this>;

  interface: ITransferRestrictionPolicyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  eligibilityRequired: TypedContractMethod<[], [boolean], "view">;

  enforcementEnabled: TypedContractMethod<[], [boolean], "view">;

  jurisdictionRequired: TypedContractMethod<[], [boolean], "view">;

  lockupUntil: TypedContractMethod<[wallet: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "eligibilityRequired"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "enforcementEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "jurisdictionRequired"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lockupUntil"
  ): TypedContractMethod<[wallet: AddressLike], [bigint], "view">;

  filters: {};
}
