/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IComplianceGate,
  IComplianceGateInterface,
} from "../../../contracts/interfaces/IComplianceGate";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "wallet",
        type: "address",
      },
    ],
    name: "validate",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IComplianceGate__factory {
  static readonly abi = _abi;
  static createInterface(): IComplianceGateInterface {
    return new Interface(_abi) as IComplianceGateInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IComplianceGate {
    return new Contract(address, _abi, runner) as unknown as IComplianceGate;
  }
}
