/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFreezeRegistry,
  IFreezeRegistryInterface,
} from "../../../contracts/interfaces/IFreezeRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "selector",
        type: "bytes4",
      },
    ],
    name: "isFrozenFunction",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "seriesId",
        type: "bytes32",
      },
    ],
    name: "isFrozenSeries",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "wallet",
        type: "address",
      },
    ],
    name: "isFrozenWallet",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFreezeRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IFreezeRegistryInterface {
    return new Interface(_abi) as IFreezeRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFreezeRegistry {
    return new Contract(address, _abi, runner) as unknown as IFreezeRegistry;
  }
}
