/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGovernanceControl,
  IGovernanceControlInterface,
} from "../../../contracts/interfaces/IGovernanceControl";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "isCouncilSigner",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "isGuardian",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IGovernanceControl__factory {
  static readonly abi = _abi;
  static createInterface(): IGovernanceControlInterface {
    return new Interface(_abi) as IGovernanceControlInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGovernanceControl {
    return new Contract(address, _abi, runner) as unknown as IGovernanceControl;
  }
}
