/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IOperationsRegistry,
  IOperationsRegistryInterface,
} from "../../../contracts/interfaces/IOperationsRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "checkpointId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "scope",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "evidenceHash",
        type: "bytes32",
      },
      {
        internalType: "uint64",
        name: "periodStart",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "periodEnd",
        type: "uint64",
      },
    ],
    name: "recordAuditCheckpoint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IOperationsRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IOperationsRegistryInterface {
    return new Interface(_abi) as IOperationsRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IOperationsRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IOperationsRegistry;
  }
}
