/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRiskEnforcement,
  IRiskEnforcementInterface,
} from "../../../contracts/interfaces/IRiskEnforcement";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "wallet",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "action",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "checkLimits",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "wallet",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "action",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "consumeQuota",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRiskEnforcement__factory {
  static readonly abi = _abi;
  static createInterface(): IRiskEnforcementInterface {
    return new Interface(_abi) as IRiskEnforcementInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRiskEnforcement {
    return new Contract(address, _abi, runner) as unknown as IRiskEnforcement;
  }
}
