/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRiskScoreRegistry,
  IRiskScoreRegistryInterface,
} from "../../../contracts/interfaces/IRiskScoreRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "entityId",
        type: "bytes32",
      },
    ],
    name: "isScoreActiveEntity",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "subjectId",
        type: "bytes32",
      },
    ],
    name: "isScoreActiveSubject",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "wallet",
        type: "address",
      },
    ],
    name: "isScoreActiveWallet",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "entityId",
        type: "bytes32",
      },
    ],
    name: "scoreOfEntity",
    outputs: [
      {
        internalType: "enum IRiskScoreRegistry.RiskLevel",
        name: "level",
        type: "uint8",
      },
      {
        internalType: "uint32",
        name: "version",
        type: "uint32",
      },
      {
        internalType: "uint64",
        name: "validFrom",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "validTo",
        type: "uint64",
      },
      {
        internalType: "bytes32",
        name: "justificationHash",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "subjectId",
        type: "bytes32",
      },
    ],
    name: "scoreOfSubject",
    outputs: [
      {
        internalType: "enum IRiskScoreRegistry.RiskLevel",
        name: "level",
        type: "uint8",
      },
      {
        internalType: "uint32",
        name: "version",
        type: "uint32",
      },
      {
        internalType: "uint64",
        name: "validFrom",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "validTo",
        type: "uint64",
      },
      {
        internalType: "bytes32",
        name: "justificationHash",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "wallet",
        type: "address",
      },
    ],
    name: "scoreOfWallet",
    outputs: [
      {
        internalType: "enum IRiskScoreRegistry.RiskLevel",
        name: "level",
        type: "uint8",
      },
      {
        internalType: "uint32",
        name: "version",
        type: "uint32",
      },
      {
        internalType: "uint64",
        name: "validFrom",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "validTo",
        type: "uint64",
      },
      {
        internalType: "bytes32",
        name: "justificationHash",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "entityId",
        type: "bytes32",
      },
      {
        internalType: "enum IRiskScoreRegistry.RiskLevel",
        name: "level",
        type: "uint8",
      },
      {
        internalType: "uint32",
        name: "version",
        type: "uint32",
      },
      {
        internalType: "uint64",
        name: "validFrom",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "validTo",
        type: "uint64",
      },
      {
        internalType: "bytes32",
        name: "justificationHash",
        type: "bytes32",
      },
    ],
    name: "setEntityScore",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "wallet",
        type: "address",
      },
      {
        internalType: "enum IRiskScoreRegistry.RiskLevel",
        name: "level",
        type: "uint8",
      },
      {
        internalType: "uint32",
        name: "version",
        type: "uint32",
      },
      {
        internalType: "uint64",
        name: "validFrom",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "validTo",
        type: "uint64",
      },
      {
        internalType: "bytes32",
        name: "justificationHash",
        type: "bytes32",
      },
    ],
    name: "setWalletScore",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "wallet",
        type: "address",
      },
    ],
    name: "walletToSubjectId",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class IRiskScoreRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IRiskScoreRegistryInterface {
    return new Interface(_abi) as IRiskScoreRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRiskScoreRegistry {
    return new Contract(address, _abi, runner) as unknown as IRiskScoreRegistry;
  }
}
